services:
  postgres:
    image: postgres:15@sha256:3b0d656f5fff31c7d8a64f500a703dcf3f35e98ce78f602831a73059a5e6a012
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wg_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:9-alpine
    command: migrate
    volumes: 
      - ./mogrations:/flyway/sql:ro
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/wg_demo
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_BASELINE_ON_MIGRATE: true
    depends_on:
      postgres:
        condition:service_healthy
healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
