services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/wg
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: wg
      DB_PASSWORD: wg

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: wg
      POSTGRES_PASSWORD: wg
      POSTGRES_DB: wg_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wg -d wg_development"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
